# Generated by Django 5.0.6 on 2024-07-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('PS', 'PlayStation 1'), ('PS', 'PlayStation 2'), ('PS', 'PlayStation 3'), ('PS', 'PlayStation 4'), ('PS', 'PlayStation 5'), ('PC', 'HP Victus 15'), ('PC', 'HP Victus 16'), ('PC', 'Lenovo Legion 5'), ('PC', 'ASUS TUF F15 GAMING'), ('PC', 'ASUS ROG G15'), ('G', 'Dark Soul'), ('G', 'God Of War 2'), ('G', 'God Of War 4'), ('G', 'Mass Effect 3'), ('G', 'Resident Evil 4 Remake'), ('G', 'Silent Hill'), ('G', 'Spiderman'), ('G', 'The Legend of Zelda: Breath of the Wild'), ('M', 'Mando para PlayStation 1'), ('M', 'Mando para PlayStation 2'), ('M', 'Mando para PlayStation 3'), ('M', 'Mando para PlayStation 4'), ('M', 'Mando para PlayStation 5')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
