# Generated by Django 5.0.6 on 2024-07-10 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_prodapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('San Salvador', 'San Salvador'), ('La Libertad', 'La Libertad'), ('San Miguel', 'San Miguel'), ('Santa Ana', 'Santa Ana'), ('Usulutan', 'Usulután'), ('Sonsonate', 'Sonsonate'), ('Ahuachapan', 'Ahuachapán'), ('La Paz', 'La Paz'), ('La Union', 'La Union'), ('San Vicente', 'San Vicente'), ('Chalatenango', 'Chalatenango'), ('Cuscatlan', 'Cuscutlán'), ('Morazan', 'Morazán'), ('Cabanas', 'Cabañas')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
