# Generated by Django 5.0.6 on 2024-07-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_targeta_delete_customer'),
    ]

